export const db = [
    {
        "id": "6f23baea-b3c0-465b-9ecc-446ac5834c69",
        "content": null,
        "created_at": "2022-02-10 20:59:29.011",
        "updated_at": "2022-07-18 22:37:32.105",
        "published_at": "2022-02-11 19:55:24.169",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "React web Developer at Studio4D",
        "description": "Studio 4D offers different experiences of virtual reality created through apps like Unreal Engine and served through web apps with services on the cloud as AWS. I was responsible for the first implementation of React on projects of experience and frameworks as tailwind associated, the communication with a node server and Unreal platform. Also, I do other tasks associated with the position of IT. I understood better the work in group and different project methodologies. I integrated the team of developers in the future different new application and structure!",
        "url_image": "/img/react dev studio.png",
        "url_github": null,
        "url_video": null,
        "url_deploy": null,
        "priority": true,
        "technologies": [
            "React",
            "Tailwind",
            "Express",
            "Storybook react"
        ]
    },
    {
        "id": "71c0bb50-101d-4e72-a947-456f78af495f",
        "content": null,
        "created_at": "2022-02-10 20:58:57.569",
        "updated_at": "2022-02-11 19:55:26.284",
        "published_at": "2022-02-11 19:55:26.142",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "PWA - Garden app",
        "description": "This app is a draft. I would like to show this from an early stage. The objective is to understand the concept of pwa. Practising the written code and implementing. Different new web technologies , with Svelte framework firebase and more.",
        "url_image": "/img/eraser.png",
        "url_github": "https://github.com/pablodelfante/svelte-proyects/tree/pwa-garden",
        "url_video": null,
        "url_deploy": null,
        "priority": false,
        "technologies": [
            "Svelte",
            "PWA",
            "Firebase",
            "Bootstrap"
        ]
    },
    {
        "id": "f7e1cd51-cb94-4e4b-8ebd-a30713e736d6",
        "content": null,
        "created_at": "2022-02-10 20:58:22.686",
        "updated_at": "2022-02-11 19:55:27.711",
        "published_at": "2022-02-11 19:55:27.572",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "Socket.io - Express Chat App",
        "description": "Here the socket io implementation on chat application is shown as a recently acquired technology. I use cookies management and a basic system of sessions to register the current user.",
        "url_image": "/img/chat-app.png",
        "url_github": "https://github.com/pablodelfante/socket-chat-app",
        "url_video": null,
        "url_deploy": "https://first-socket-chat-app.herokuapp.com/",
        "priority": false,
        "technologies": [
            "Express",
            "Tailwind CSS",
            "Socket.io",
            "nodemon"
        ]
    },
    {
        "id": "57765139-6e57-4915-be50-b1cbafc120d0",
        "content": "",
        "created_at": "2022-02-09 19:39:29.82",
        "updated_at": "2022-02-13 20:27:50.901",
        "published_at": "2022-02-09 19:40:17.774",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "PWA - This web site",
        "description": "This site was born out of the need to show works that have produced technological changes inside me. I try to show my profile both as a professional and as an individual. Every day I try to get better, to learn, explore and in this way be a better person enjoying what I do.",
        "url_image": "/img/audits.jpg",
        "url_github": "https://github.com/pablodelfante/works-next-app",
        "url_video": "",
        "url_deploy": "",
        "priority": true,
        "technologies": [
            "Next js",
            "PWA",
            "Tailwind",
            "Strapi",
            "Docker",
            "GraphQL",
            "Figma"
        ]
    },
    {
        "id": "d0913cd7-6330-4a9d-b6be-a5520ab83d84",
        "content": null,
        "created_at": "2022-02-10 20:57:50.173",
        "updated_at": "2022-02-11 19:55:29.137",
        "published_at": "2022-02-11 19:55:28.996",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "P2 - Watch Shop",
        "description": "Academic project, use PHP and MYSQL as database, the proposal was do two sections in the target. One where you had the client and another, with a dashboard panel for content managment. I underlineed the personal growth out of the proyect and the evolution on structures of data and organization, work methodologies and experience obtained with front and back tools. This opened experiences and doors to other projects with node and different databases.",
        "url_image": "/img/watch shop.jpg",
        "url_github": "https://github.com/pablodelfante/P2-obligatorio",
        "url_video": "https://www.youtube.com/embed/2Uspqad9kaU",
        "url_deploy": null,
        "priority": false,
        "technologies": [
            "PHP",
            "MySQL",
            "BrowserSync"
        ]
    },
    {
        "id": "9970d36a-c4e6-4d71-8c66-8559e3b0f04e",
        "content": null,
        "created_at": "2022-02-10 20:57:13.852",
        "updated_at": "2022-02-11 19:55:30.376",
        "published_at": "2022-02-11 19:55:30.236",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "DW3 - Neuralink Redesign",
        "description": "Redesign of the web Neuralink, the objective of the work was to get a website and doing the redesign. I focused on UX and project structure, made a performance improvement in comparison with the original website, overall produce fast and more fluid navegation.",
        "url_image": "/img/dw3-neuralink.jpeg",
        "url_github": "https://github.com/pablodelfante/W3-Obligatorio1",
        "url_video": "https://www.youtube.com/embed/zwcDITgrw-0",
        "url_deploy": "https://pablo-university.github.io/W3-Obligatorio1/src/",
        "priority": false,
        "technologies": [
            "HTML",
            "CSS",
            "JS",
            "Gulp"
        ]
    },
    {
        "id": "9970d36a-c4e6-4d71-8c66-8559e3b0f04se",
        "content": "### Node integration\nThe system, manage the users getting the data from localstorage or local with ajax, save the data on localstorage and after that try use the server express who manage the local saved. If you download the proyect on local machine, intall the packages and start the server!\n\n1. npm install\n2. node serverLocal.js\n\n**NOTE: **To start session, you can use ‘1’ as user and pasword!",
        "created_at": "2022-02-10 20:55:19.89",
        "updated_at": "2022-02-11 19:54:15.743",
        "published_at": "2022-02-11 19:54:15.602",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "JS - Dashboard people managment",
        "description": "Dashboard for people managment, created with Javascript vanilla, the focus was to show the skills obtained with javascript and jquery like library to understand the libraries concept. And other integratios!",
        "url_image": "/img/dashboard-js.png",
        "url_github": "https://github.com/pablodelfante/P1-obligatorio",
        "url_video": null,
        "url_deploy": "https://pablo-university.github.io/P1-obligatorio/public/index.html",
        "priority": false,
        "technologies": [
            "HTML",
            "JavaScript",
            "Figma",
            "SCSS",
            "Node js"
        ]
    },
    {
        "id": "9970d36a-c4e6-4d71-8c66-8559e3b0f04es",
        "content": "",
        "created_at": "2022-02-10 20:55:59.207",
        "updated_at": "2022-02-11 19:54:33.387",
        "published_at": "2022-02-11 19:54:33.246",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "DW2 - Strip to Australia",
        "description": " Overall, it is about tourist information, general information about Australia, the target of the web is to show differents skills thgrough with techologies as CSS, SCSS or the different libraries implementation to do the web site.",
        "url_image": "/img/dw2-viaje-a-australia.png",
        "url_github": "https://github.com/pablodelfante/W2-obligatorio2",
        "url_video": null,
        "url_deploy": "https://pablo-university.github.io/W2-obligatorio2/",
        "priority": false,
        "technologies": [
            "HTML",
            "CSS",
            "SASS",
            "JavaScript",
            "Bibliotecas CSS y JS"
        ]
    },
    {
        "id": "9970d36a-c4e6-4d71-8cx66-8559e3b0f04es",
        "content": null,
        "created_at": "2022-02-10 20:56:37.876",
        "updated_at": "2022-02-11 19:55:31.791",
        "published_at": "2022-02-11 19:55:31.652",
        "created_by_id": 1,
        "updated_by_id": 1,
        "title": "Prototype - NATURAL",
        "description": "Academic project, the target was to understand matters and different proceses in diciplines such as UX and UI, had and introduction to the digital interfaces world web develop.",
        "url_image": "/img/prototype-NATURAL.jpg",
        "url_github": null,
        "url_video": "https://www.youtube.com/embed/3cLymG7PwM4",
        "url_deploy": null,
        "priority": false,
        "technologies": [
            "Figma",
            "Photoshop",
            "Ilustrator"
        ]
    }
]