export const db = [
    {
        id: '71c0bb50-101d-4e72-a947-456f78af495f',
        content: null,
        title: 'PWA - Garden app',
        description:
            'This app is a draft. I would like to show this from an early stage. The objective is to understand the concept of pwa. Practising the written code and implementing. Different new web tags , with Svelte framework firebase and more.',
        url_image: '/img/eraser.png',
        url_github:
            'https://github.com/pablodelfante/svelte-proyects/tree/pwa-garden',
        url_video: null,
        url_deploy: null,
        priority: false,
        tags: ['Svelte', 'PWA', 'Firebase', 'Bootstrap'],
        draft: false,
    },
    {
        id: 'f7e1cd51-cb94-4e4b-8ebd-a30713e736d6',
        content: null,
        title: 'Socket.io - Express Chat App',
        description:
            'Here the socket io implementation on chat application is shown as a recently acquired technology. I use cookies management and a basic system of sessions to register the current user.',
        url_image: '/img/chat-app.png',
        url_github: 'https://github.com/pablodelfante/socket-chat-app',
        url_video: null,
        url_deploy: null,
        priority: false,
        tags: ['Express', 'Tailwind CSS', 'Socket.io', 'nodemon'],
        draft: false,
    },
    {
        id: '57765139-6e57-4915-be50-b1cbafc120d0',
        content: '',
        title: 'PWA - This web site',
        description:
            'This site was born out of the need to show works that have produced technological changes inside me. I try to show my profile both as a professional and as an individual. Every day I try to get better, to learn, explore and in this way be a better person enjoying what I do.',
        url_image: '/img/site.png',
        url_github: 'https://github.com/pablodelfante/works-next-app',
        url_video: '',
        url_deploy: '',
        priority: true,
        tags: [
            'Next js',
            'PWA',
            'Tailwind',
            'Strapi',
            'Docker',
            'GraphQL',
            'Figma',
        ],
        draft: false,
    },
    {
        id: 'd0913cd7-6330-4a9d-b6be-a5520ab83d84',
        content: null,
        title: 'P2 - Watch Shop',
        description:
            'Academic project, use PHP and MYSQL as database, the proposal was do two sections in the target. One where you had the client and another, with a dashboard panel for content managment. I underlineed the personal growth out of the proyect and the evolution on structures of data and organization, work methodologies and experience obtained with front and back tools. This opened experiences and doors to other projects with node and different databases.',
        url_image: '/img/watch shop.jpg',
        url_github: 'https://github.com/pablodelfante/P2-obligatorio',
        url_video: 'https://www.youtube.com/embed/2Uspqad9kaU',
        url_deploy: null,
        priority: false,
        tags: ['PHP', 'MySQL', 'BrowserSync'],
        draft: false,
    },
    {
        id: '9970d36a-c4e6-4d71-8c66-8559e3b0f04e',
        content: null,
        title: 'DW3 - Neuralink Redesign',
        description:
            'Redesign of the web Neuralink, the objective of the work was to get a website and doing the redesign. I focused on UX and project structure, made a performance improvement in comparison with the original website, overall produce fast and more fluid navegation.',
        url_image: '/img/dw3-neuralink.jpeg',
        url_github: 'https://github.com/pablodelfante/W3-Obligatorio1',
        url_video: 'https://www.youtube.com/embed/zwcDITgrw-0',
        url_deploy: 'https://pablo-university.github.io/W3-Obligatorio1/src/',
        priority: false,
        tags: ['HTML', 'CSS', 'JS', 'Gulp'],
        draft: false,
    },
    {
        id: '9970d36a-c4e6-4d71-8c66-8559e3b0f04es',
        content: '',
        title: 'DW2 - Strip to Australia',
        description:
            'Overall, it is about tourist information, general information about Australia, the target of the web is to show differents skills thgrough with techologies as CSS, SCSS or the different libraries implementation to do the web site.',
        url_image: '/img/dw2-viaje-a-australia.png',
        url_github: 'https://github.com/pablodelfante/W2-obligatorio2',
        url_video: null,
        url_deploy: 'https://pablo-university.github.io/W2-obligatorio2/',
        priority: false,
        tags: ['HTML', 'CSS', 'SASS', 'JavaScript', 'Bibliotecas CSS y JS'],
        draft: false,
    },
    {
        id: '9970d36a-c4e6-4d71-8cx66-8559e3b0f04es',
        content: null,
        title: 'Prototype - NATURAL',
        description:
            'Academic project, the target was to understand matters and different proceses in diciplines such as UX and UI, had and introduction to the digital interfaces world web develop.',
        url_image: '/img/prototype-NATURAL.jpg',
        url_github: null,
        url_video: 'https://www.youtube.com/embed/3cLymG7PwM4',
        url_deploy: null,
        priority: false,
        tags: ['Figma', 'Photoshop', 'Ilustrator'],
        draft: false,
    },
    {
        id: '11f6ad8ec52a2984abaafd7c3b516503785c2072',
        content: null,
        title: 'Web workers',
        description:
            'I have recently been learning about Web Workers, I had a curiosity about functionality and can have deep knowledge about this. I have Always been curious about javascript, technical details and for example, the event loop, have paved the way for me to get more knowledge about technical improvement, and performance and this knowledge has led me to search and investigate other tags, such as web APIs, PWA’s and others. I have thought of a process that requires some more powerful for example, image management and others. My first point to start with was not blocking the main thread on js. This was my point for learning and investigating other alternative to do some tasks that required more power in the background.',
        url_image: '/img/web-workers.jpg',
        url_github: 'https://github.com/pablo-learn/workers',
        url_video: null,
        url_deploy: null,
        priority: true,
        tags: ['Node', 'Expressjs', 'Web Workers', 'SSR'],
        draft: false,
    },
]
